[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
pushsolanalocker = "3zrWaMknHTRQpZSxY4BvQxw9TStSXiHcmcp3NMPTFkke"

[registry]
url = "https://api.apr.dev"

[provider]
# cluster = "Localnet"
cluster = "https://api.devnet.solana.com"
# cluster = "https://api.testnet.solana.com"
wallet = "./upgrade-keypair.json"


[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
