[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
pushsolanagateway = "CFVSincHYbETh2k7w6u1ENEkjbSLtveRCEBupKidw2VS"  
pushsolanalocker = "3zrWaMknHTRQpZSxY4BvQxw9TStSXiHcmcp3NMPTFkke"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "./upgrade-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
