[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
pushsolanalocker = "3zrWaMknHTRQpZSxY4BvQxw9TStSXiHcmcp3NMPTFkke"
pushsolanagateway = "9nokRuXvtKyT32vvEQ1gkM3o8HzNooStpCuKuYD8BoX5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "./upgrade-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
